dist: bionic
arch:
  - amd64
  - arm64
language: bash
env:
  - SNAPCRAFT_BUILD_ENVIRONMENT=host
before_install:
  # Yes, we try to install snapcraft twice, as it is necessary for now on arm64!
  # See https://github.com/lxc/lxd/issues/3421
  - sudo -E snap install --classic snapcraft || true
  - sudo -E snap install --classic snapcraft
  - sudo -E apt-get -yq --no-install-suggests --no-install-recommends install nginx-light python3-venv libssl-dev
  - sudo -E /etc/init.d/nginx stop
install:
  - git clone https://github.com/certbot/certbot.git certbot --branch v0.40.1
  - certbot/tools/strip_hashes.py certbot/letsencrypt-auto-source/pieces/dependency-requirements.txt > certbot/constraints.txt
before_script:
  - snapcraft
script:
  - sudo snap install --dangerous --classic *.snap
  - bash test.sh
deploy:
  'on':
    branch: master
  provider: snap
  snap: certbot_*.snap
  channel: edge
  skip_cleanup: true
notifications:
  email:
    recipients: [robie.basak@canonical.com]
    on_failure: change
