dist: xenial
language: bash
script: docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt-get update -qq && cd $(pwd) && snapcraft" && sudo apt-get -y install snapd && sudo snap install --dangerous --classic *.snap && sudo bash test.bash
sudo: required
services:
- docker
deploy:
  'on':
    branch: master
  provider: snap
  snap: certbot_*.snap
  channel: edge
  skip_cleanup: true
notifications:
  email:
    recipients: [robie.basak@canonical.com]
    on_failure: change
