language: bash
before_install:
  - |
    sudo -E apt-get -yq --no-install-suggests --no-install-recommends install nginx-light
    sudo -E /etc/init.d/nginx stop
install:
  - git clone https://github.com/certbot/certbot.git certbot --branch master
  - certbot/tools/strip_hashes.py certbot/letsencrypt-auto-source/pieces/dependency-requirements.txt > certbot/constraints.txt
script:
  - docker run -v $(pwd):$(pwd) -t snapcore/snapcraft sh -c "apt-get update -qq && apt-get install -qq git && cd $(pwd) && snapcraft"
  - sudo snap install --dangerous --classic *.snap
  - sudo bash test.sh
addons:
  apt:
    packages:
    - snapd
    - python3-venv
    - python3-requests
    - python3-packaging
services:
  - docker
deploy:
  'on':
    branch: master
  provider: snap
  snap: certbot_*.snap
  channel: edge
  skip_cleanup: true
notifications:
  email:
    recipients: [robie.basak@canonical.com]
    on_failure: change
